config/routes.rb
CareerSupprtCenter::Application.routes.draw do
    match'/career_support_center' =>'career_support_center#index'
    match'/career_support_cente/sitemap' =>'career_support_center#sitemap'
    resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :email_address, :emergency_contact_address, :grade, :name, :number, :phone_number, :protector_phone_number, :school_register_number, :subject
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/career_support_center_controller.rb
class CareerSupportCenterController < ApplicationController
    def index
    end
    def sitemap
    end
end

app/controllers/students_controller.rb
# coding: utf-8
class StudentsController < ApplicationController

  def index
    @students = Student.all

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @student=Student.new
  end

  def create
    @student=Student.new(params[:student])
    @student.save
    redirect_to(@student,:notice=>'ユーザー情報の登録に成功しました')
  end

  def show
      @student=Student.find(params[:id])
  end

  def edit
      @student=Student.find(params[:id])
  end

  def update
    @student=Student.find(params[:id])
    @student.update_attributes(params[:student])
    redirect_to(@student,:notice=>'ユーザー情報の更新に成功しました')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/career_support_center_helper.rb
module CareerSupportCenterHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/career_support_center/index.html.erb
<center><h1>Career Support Center</h1></center>
<%=link_to('サイトマップ', { :controller => 'career_support_center',:action =>'sitemap'}) %></br>
<%=link_to('学生情報新規登録', new_student_path) %></br>

app/views/career_support_center/sitemap.html.erb
このサイトは香川高専での進路希望調査システムです。</br>
まず始めにユーザー情報を登録してください。</br>

<%=link_to('Back',{ :controller => 'career_support_center' ,:action=>'index'})%>

app/views/layouts/_footer.html.erb
<div id="footer">
    -power by <strong>Ruby on Rails 3.2.8 </strong>
</div>

app/views/layouts/_header.html.erb
<div id="header">
    <%=link_to image_tag('/sitelogo.png', :size => '129x57', :alt => 'サイトロゴ'),{ :controller => 'career_support_center',:action=>'index'} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CareerSupprtCenter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
        <div id="content">
            <%= yield %>
        </div>
    <%= render 'layouts/footer' %>
</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
<% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% if false %>
url optionはそのフォームの送信先を示す
<% end %>

<fieldset>
<legend>学生情報</legend>
<div class="field">
    <%= f.label :学籍番号%><br />
    <%= f.number_field :school_register_number,placeholder:"08132" %>
</div>
<div class="field">
    <%= f.label :学生名%><br />
    <%= f.text_field :name,placeholder:"詫間太郎" %>
</div>
<div class="field">
    <%= f.label :学年%><br />
     <%= f.select(:grade,['本科1年','本科2年','本科3年','本科3年','本科4年','本科5年','専攻科1年','専攻科2年'],{:include_blank=>'選択してください'},{:class => 'pub'}) %>
</div>
<div class="field">
    <%= f.label :出席番号%><br />
    <%= f.number_field :number,placeholder:"18" %>
</div>
<div class="field">
    <%= f.label :学科%><br />
    <%= f.select(:subject,['情報工学科','制御工学科','通信工学科','電子工学科'],{:include_blank=>'選択してください'},{:class => 'pub'}) %>
</div>
<div class="field">
    <%= f.label :携帯電話番号%><br />
    <%= f.telephone_field :phone_number,placeholder:"09012345678" %>
</div>
<div class="field">
    <%= f.label :メールアドレス%><br />
    <%= f.email_field :email_address,placeholder:"takuma@example.com" %>
</div>
<div class="field">
    <%= f.label :保護者の携帯電話番号%><br />
    <%= f.text_field :protector_phone_number,placeholder:"09012345678" %>
</div>
<div class="field">
    <%= f.label :緊急連絡先%><br />
    <%= f.text_area :emergency_contact_address,placeholder:"○○県△△市□□町123-456" %>
</div>
</fieldset>

<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>ユーザー情報編集</h1>

<%= render 'form' %>

<%=link_to('Back',{ :controller => 'career_support_center' ,:action=>'index'})%>

app/views/students/index.html.erb
<table>
<thead>
<tr>
<th>name</th>
<th>number</th>
<th>grade</th>
<th>subject</th>
<th>phone_number</th>
<th>emergency_contact_address</th>
<th>protector_phone_number</th>
<th>email_address</th>
<th>school_register_number</th>
<th>created_at</th>
<th>updated_at</th>
</tr>
</thead>

<tbody>
<% @students.each do |student| %>
<tr>
  <td><%= student.name %></td>
  <td><%= student.number %></td>
  <td><%= student.grade %></td>
  <td><%= student.subject %></td>
  <td><%= student.phone_number %></td>
  <td><%= student.emergency_contact_address %></td>
  <td><%= student.protector_phone_number %></td>
  <td><%= student.email_address %></td>
  <td><%= student.school_register_number %></td>
  <td><%= student.created_at %></td>
  <td><%= student.updated_at %></td>
</tr>
<% end %>
</tbody>

app/views/students/new.html.erb
# coding: utf-8
<h2>学生情報登録画面</h2>
<%= render 'form' %>
<%=link_to('Back',{ :controller => 'career_support_center' ,:action=>'index'})%>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<fieldset>
<legend>学生情報</legend>
<p>
    <b>学籍番号:</b>
    <%=@student.school_register_number%>
</p>
<p>
    <b>学生名:</b>
    <%=@student.name%>
</p>
<p>
    <b>学年:</b>
     <%=@student.grade %>
</p>   
    <b>出席番号:</b>
    <%=@student.number%>
<p>
    <b>学科:</b>
    <%= @student.subject%>
</p>
<p>
    <b>携帯電話番号:</b>
    <%= @student.phone_number %>
</p>
<p>
    <b>メールアドレス:</b>
    <%= @student.email_address%>
</p>
<p>
    <b>保護者の携帯電話番号:</b>
    <%=@student.protector_phone_number %>
</p>
<p>
    <b>緊急連絡先:</b>
    <%= @student.emergency_contact_address%>
</p>
<%=link_to('編集', edit_student_path) %>
</fieldset>
<%=link_to('Back',{ :controller => 'career_support_center' ,:action=>'index'})%>